# Generated by Django 5.1.1 on 2024-09-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IgnoredRedditor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("username", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Redditor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("age", models.IntegerField()),
                ("iq", models.IntegerField()),
                ("last_processed", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_processed", models.DateTimeField(auto_now=True)),
                ("sentiment_polarity", models.FloatField()),
                ("url", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnprocessableRedditor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("username", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnprocessableThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("url", models.URLField(unique=True)),
            ],
        ),
    ]
