# Generated by Django 5.1.3 on 2024-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="If `True`, the `StatusMessage` will be included in the /api/v1/messages/ response. Set `active_is_computed` to `True` if this field is dynamically set in signals.py.",
                    ),
                ),
                (
                    "active_is_computed",
                    models.BooleanField(
                        default=False,
                        help_text="Set this to `True` if `StatusMessage.active` is dynamically set in signals.py.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("danger", "danger"),
                            ("info", "info"),
                            ("warning", "warning"),
                        ],
                        help_text="Corresponds to how the message is rendered in the extension Status tab.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Information that should be conveyed to users in the extension Status tab."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the `StatusMessage`.",
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="api",
                        help_text="Describes where the `StatusMessage` originated from ('api' / 'extension').",
                    ),
                ),
            ],
        ),
    ]
