version: "3.8"
services:
  app:
    image: "spiceworm/${APP_NAME}/app:0.1.0"
    build:
      context: "./app"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL: "${OPENAI_MODEL}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_USER: "${POSTGRES_USER}"
      REDIS_HOST: "${REDIS_HOST}"
      SECRET_KEY: "${SECRET_KEY}"
    ports:
      - "8888:80"
    volumes:
      - "./app:/app"

  db:
    image: "postgres:16.3-bookworm"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - "/data/${APP_NAME}/db:/var/lib/postgresql/data"
    networks:
      default:
        aliases:
          - "db"

  redis:
    image: "redis:7.4.0-bookworm"
    hostname: "redis"
    volumes:
      - "/data/${APP_NAME}/redis:/data"
