name: "reecon-backend"

services:
  server:
    image: "${REGISTRY_URL}/${CONTAINER_REPO}/${APP_NAME}/server:${VERSION}"
    build:
      context: "."
    environment:
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      APP_NAME: "${APP_NAME}"
      DEBUG: "${DEBUG}"
      LOG_LEVEL: "${LOG_LEVEL}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_SSL: "${POSTGRES_SSL}"
      POSTGRES_USER: "${POSTGRES_USER}"
      REDDIT_API_CLIENT_ID: "${REDDIT_API_CLIENT_ID}"
      REDDIT_API_CLIENT_SECRET: "${REDDIT_API_CLIENT_SECRET}"
      REDDIT_API_PASSWORD: "${REDDIT_API_PASSWORD}"
      REDDIT_API_USERNAME: "${REDDIT_API_USERNAME}"
      REDDIT_API_USER_AGENT: "${REDDIT_API_USER_AGENT}"
      REDIS_HOST: "${REDIS_HOST}"
      SECRET_KEY: "${SECRET_KEY}"
      VERSION: "${VERSION}"
    ports:
      - "8888:80"
    volumes:
      - "./server:/server"

  db:
    image: "postgres:16.3-bookworm"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - "/data/${APP_NAME}/db:/var/lib/postgresql/data"
    networks:
      default:
        aliases:
          - "db"

  redis:
    image: "redis:7.4.0-bookworm"
    hostname: "redis"
    volumes:
      - "/data/${APP_NAME}/redis:/data"
