services:
  db:
    # match digitalocean "postgresql" db version
    image: "postgres:16.6-bookworm"
    environment: &db_env
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "123abc"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "disable"
      POSTGRES_USER: "postgres"
    networks:
      default:
        aliases:
          - db

  redis:
    # match digitalocean "caching" db version
    image: "redis:7.2.6-bookworm"
    hostname: "redis"

  reecon_tests:
    build:
      context: "reecon"
    environment: &reecon_env
      <<: *db_env
      DEBUG: "False"  # simulate production
      REDIS_HOST: "redis"
      SECRET_KEY: "123abc"
    entrypoint: "uvx --with tox-uv tox ${TOX_ARGS:-}"
    # Allows us to attach to the container when a pdb shell opens from encountering a test error
    stdin_open: true
    tty: true

  server_tests:
    build:
      context: "server"
    depends_on:
      # run tests sequentially so it is easier to see when and where a failure occurs
      reecon_tests:
        condition: service_completed_successfully
    environment:
      <<: *reecon_env
      APP_NAME: "reecon"
      DEFAULT_OPENAI_API_KEY: "asdf"
      REDDIT_API_CLIENT_ID: "asdf"
      REDDIT_API_CLIENT_SECRET: "asdf"
      REDDIT_API_USER_AGENT: "asdf"
    entrypoint: "uvx --with tox-uv tox ${TOX_ARGS:-}"
    # Allows us to attach to the container when a pdb shell opens from encountering a test error
    stdin_open: true
    tty: true
