services:
  db:
    # match digitalocean "postgresql" db version
    image: "postgres:16.6-bookworm"
    environment: &db_env
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "123abc"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "disable"
      POSTGRES_USER: "postgres"
    networks:
      default:
        aliases:
          - db

  redis:
    # match digitalocean "caching" db version
    image: "redis:7.2.6-bookworm"
    hostname: "redis"

  tests:
    build:
      context: "."
    environment:
      <<: *db_env
      DEBUG: "False"  # simulate production
      REDIS_HOST: "redis"
      SECRET_KEY: "123abc"
    entrypoint: "uvx --with tox-uv tox ${TOX_ARGS:-}"
