# Generated by Django 5.1.3 on 2024-11-15 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reecon", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RedditorContextQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now=True, help_text="Date and time of creation.")),
                ("prompt", models.TextField()),
                (
                    "context",
                    models.ForeignKey(
                        help_text="The reddit redditor whose submissions were used to generate the query response.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_queries",
                        to="reecon.redditor",
                    ),
                ),
                (
                    "response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_redditor_context_query",
                        to="reecon.producedtext",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        help_text="The user who submit the context query for processing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_redditor_context_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadContextQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now=True, help_text="Date and time of creation.")),
                ("prompt", models.TextField()),
                (
                    "context",
                    models.ForeignKey(
                        help_text="The reddit thread whose submissions were used to generate the query response.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_queries",
                        to="reecon.thread",
                    ),
                ),
                (
                    "response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_thread_context_query",
                        to="reecon.producedtext",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        help_text="The user who submit the context query for processing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_thread_context_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
