# Generated by Django 5.1.3 on 2024-11-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reecon", "0002_contextquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditordata",
            name="sentiment_subjectivity",
            field=models.OneToOneField(
                default=0.5,
                help_text="The inferred sentiment subjectivity of the redditor based on their submissions.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentiment_subjectivity_redditor_data",
                to="reecon.producedfloat",
            ),
        ),
        migrations.AddField(
            model_name="threaddata",
            name="sentiment_subjectivity",
            field=models.OneToOneField(
                default=0.5,
                help_text="The inferred sentiment subjectivity of the thread based on the submissions.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentiment_subjectivity_thread_data",
                to="reecon.producedfloat",
            ),
        ),
        migrations.AlterField(
            model_name="redditordata",
            name="sentiment_polarity",
            field=models.OneToOneField(
                default=0.0,
                help_text="The inferred sentiment polarity of the redditor based on their submissions.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentiment_polarity_redditor_data",
                to="reecon.producedfloat",
            ),
        ),
        migrations.AlterField(
            model_name="threaddata",
            name="sentiment_polarity",
            field=models.OneToOneField(
                default=0.0,
                help_text="The inferred sentiment polarity of the thread based on the submissions.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentiment_polarity_thread_data",
                to="reecon.producedfloat",
            ),
        ),
    ]
