# Generated by Django 5.1.3 on 2024-11-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reecon", "0003_sentimentsubjectivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditorcontextquery",
            name="total_inputs",
            field=models.IntegerField(
                default=0, help_text="The total number of inputs used when processing the context query."
            ),
        ),
        migrations.AddField(
            model_name="redditordata",
            name="total_inputs",
            field=models.IntegerField(default=0, help_text="The total number of inputs used when processing the data."),
        ),
        migrations.AddField(
            model_name="threadcontextquery",
            name="total_inputs",
            field=models.IntegerField(
                default=0, help_text="The total number of inputs used when processing the context query."
            ),
        ),
        migrations.AddField(
            model_name="threaddata",
            name="total_inputs",
            field=models.IntegerField(default=0, help_text="The total number of inputs used when processing the data."),
        ),
    ]
