# Generated by Django 5.1.4 on 2024-12-04 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reecon", "0004_totalinputs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnprocessableRedditorContextQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now=True, help_text="Date and time of creation.")),
                ("username", models.CharField(help_text="The username of the redditor.", max_length=32, unique=True)),
                ("reason", models.TextField(help_text="The reason the entity cannot be processed.")),
                (
                    "submitter",
                    models.ForeignKey(
                        help_text="The user who submit the unprocessable redditor context query for processing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_unprocessable_redditor_context_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnprocessableThreadContextQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now=True, help_text="Date and time of creation.")),
                ("url", models.URLField(help_text="URL.", unique=True)),
                ("reason", models.TextField(help_text="The reason the entity cannot be processed.")),
                (
                    "submitter",
                    models.ForeignKey(
                        help_text="The user who submit the unprocessable thread context query for processing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_unprocessable_thread_context_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
