services:
  db:
    # match digitalocean "postgresql" db version
    image: "postgres:16.6-bookworm"
    environment: &db_env
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "123abc"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "disable"
      POSTGRES_USER: "postgres"
    networks:
      default:
        aliases:
          - db

  reecon:
    image: "reecon:0.3.9"
    build:
      context: "../reecon"
    restart: "no"

  redis:
    # match digitalocean "caching" db version
    image: "redis:7.2.6-bookworm"
    hostname: "redis"

  tests:
    build:
      context: "."
    depends_on:
      reecon:
        condition: service_completed_successfully
    environment:
      <<: *db_env
      APP_NAME: "reecon"
      DEBUG: "False"  # simulate production
      DEFAULT_OPENAI_API_KEY: "asdf"
      REDIS_HOST: "redis"
      REDDIT_API_CLIENT_ID: "asdf"
      REDDIT_API_CLIENT_SECRET: "asdf"
      REDDIT_API_USER_AGENT: "asdf"
      SECRET_KEY: "123abc"
    entrypoint: "uvx --with tox-uv tox ${TOX_ARGS:-}"
