"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import sys

from decouple import (
    config,
    Choices,
)


BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", cast=bool, default=False)
PRODUCTION = config("PRODUCTION", cast=bool, default=False)

ROOT_URLCONF = "proj.urls"
WSGI_APPLICATION = "proj.wsgi.application"

LOG_LEVEL = config(
    "LOG_LEVEL",
    default="DEBUG" if DEBUG else "INFO",
    cast=Choices(["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]),
)

ALLOWED_HOSTS = [".reddit.com"] if PRODUCTION else ["*"]
CSRF_TRUSTED_ORIGINS = (
    [
        "https://reddit.com",
        "https://*.reddit.com",
    ]
    if PRODUCTION
    else ["http://127.0.0.1:8888"]
)
CORS_ALLOWED_ORIGINS = [
    "https://reddit.com",
    "https://old.reddit.com",
    "https://www.reddit.com",
    "http://localhost:8888",
]
CORS_ALLOW_ALL_ORIGINS = True

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_rq",
    "constance",
    "app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REDIS_HOST = config("REDIS_HOST")
REDIS_PASSWORD = config("REDIS_PASSWORD", default="")
REDIS_PORT = config("REDIS_PORT", cast=int, default=6379)
REDIS_SSL = config("REDIS_SSL", cast=bool, default=False)
REDIS_USERNAME = config("REDIS_USERNAME", default="")
REDIS_URL = f"redis{'s' if REDIS_SSL else ''}://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "DEFAULT_TIMEOUT": 360,
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"ssl_cert_reqs": None} if REDIS_SSL else {},
        },
    }
}

RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "default",
    },
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "ATOMIC_REQUESTS": True,
        "CONN_MAX_AGE": 30,
        "HOST": config("POSTGRES_HOST"),
        "NAME": config("POSTGRES_DB"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "PORT": config("POSTGRES_PORT"),
        "USER": config("POSTGRES_USER"),
        "OPTIONS": {
            "sslmode": config("POSTGRES_SSL"),
        },
    }
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
}

ACCESS_TOKEN_LIFETIME_UNIT = config("ACCESS_TOKEN_LIFETIME_UNIT", default="minutes")
ACCESS_TOKEN_LIFETIME_VALUE = config("ACCESS_TOKEN_LIFETIME_VALUE", cast=int, default=15)
ACCESS_TOKEN_LIFETIME_TIMEDELTA = timedelta(**{ACCESS_TOKEN_LIFETIME_UNIT: ACCESS_TOKEN_LIFETIME_VALUE})
REFRESH_TOKEN_LIFETIME_UNIT = config("REFRESH_TOKEN_LIFETIME_UNIT", default="days")
REFRESH_TOKEN_LIFETIME_VALUE = config("REFRESH_TOKEN_LIFETIME_VALUE", cast=int, default=30)
REFRESH_TOKEN_LIFETIME_TIMEDELTA = timedelta(**{REFRESH_TOKEN_LIFETIME_UNIT: REFRESH_TOKEN_LIFETIME_VALUE})

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": ACCESS_TOKEN_LIFETIME_TIMEDELTA,
    "REFRESH_TOKEN_LIFETIME": REFRESH_TOKEN_LIFETIME_TIMEDELTA,
}


SPECTACULAR_SETTINGS = {
    "TITLE": config("APP_NAME"),
    "DESCRIPTION": "Your project description",
    "VERSION": config("VERSION"),
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"},
    },
    "handlers": {
        "app-file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "/var/log/supervisor/gunicorn/app.log",
            "maxBytes": 15728640,  # 1024 * 1024 * 15B = 15MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "db-file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "/var/log/supervisor/gunicorn/db.log",
            "maxBytes": 15728640,  # 1024 * 1024 * 15B = 15MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "rq-file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "/var/log/supervisor/rq-worker/worker.log",
            "maxBytes": 15728640,  # 1024 * 1024 * 15B = 15MB
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "app": {
            "handlers": ["app-file"],
            "level": LOG_LEVEL,
        },
        "asyncio": {
            # suppress "Using selector: EpollSelector" when using `manage.py shell`
            "level": "WARNING",
        },
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["db-file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "rq.worker": {
            "handlers": ["rq-file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CONSTANCE_BACKEND = "constance.backends.redisd.RedisBackend"
CONSTANCE_REDIS_CONNECTION = REDIS_URL
CONSTANCE_CONFIG = {
    "CONTENT_FILTER_MIN_LENGTH": (
        config("CONTENT_FILTER_MIN_LENGTH", cast=int, default=120),
        "Minimum length required for a comment/thread to be processed. This is the length of the text after sentences "
        "containing URLs has been removed.",
    ),
    "OPENAI_MODEL": (
        config("OPENAI_MODEL"),
        "OpenAPI training model to use for prompts. https://platform.openai.com/docs/models/",
    ),
    "OPENAI_MODEL_MAX_TOKENS": (
        config("OPENAI_MODEL_MAX_TOKENS", cast=int),
        "The maximum number of tokens allowed to be submit to OPENAI_MODEL as defined by the OpenAI documentation. "
        "https://platform.openai.com/docs/models/",
    ),
    "REDDITOR_FRESHNESS_TD": (
        timedelta(days=30),
        "Defines how long `Redditor` database entries are considered fresh. Entries older than this timedelta they "
        "will be reprocessed if their username is submitted in an API request.",
        timedelta,
    ),
    "REDDITOR_MIN_SUBMISSIONS": (
        config("REDDITOR_MIN_SUBMISSIONS", cast=int, default=1),
        "The minimum number of submissions (comments + threads) that must be available for a redditor to be processed. "
        "Submissions that fail filtering requirements are considered unavailable for processing (e.g. submission "
        "content length < CONTENT_FILTER_MIN_LENGTH).",
    ),
    "THREAD_FRESHNESS_TD": (
        timedelta(minutes=15),
        "Defines how long `Thread` database entries are considered fresh. Entries older than this timedelta they will "
        "be reprocessed if their URL path is submitted in an API request.",
        timedelta,
    ),
    "THREAD_MAX_COMMENTS_PROCESSED": (
        config("THREAD_MAX_COMMENTS_PROCESSED", cast=int, default=sys.maxsize),
        "The maximum number of comments in a thread that will be considered for processing.",
    ),
    "THREAD_MIN_COMMENTS_PROCESSED": (
        config("THREAD_MIN_COMMENTS_PROCESSED", cast=int, default=1),
        "The minimum number of comments that must be present in a thread, after filtering, for processing to occur.",
    ),
    "UNPROCESSABLE_REDDITOR_EXP_TD": (
        timedelta(days=1),
        "Defines how long `UnprocessableRedditor` entries will remain in the database before being deleted. After "
        "deletion, previously unprocessable usernames will be reattempted if included in an API request.",
        timedelta,
    ),
    "UNPROCESSABLE_THREAD_EXP_TD": (
        timedelta(minutes=15),
        "Defines how long `UnprocessableThread` entries will remain in the database before being deleted. After "
        "deletion, previously unprocessable paths will be reattempted if included in an API request.",
        timedelta,
    ),
}

OPENAI_API_KEY = config("OPENAI_API_KEY")
REDDIT_API_SETTINGS = {
    "client_id": config("REDDIT_API_CLIENT_ID"),
    "client_secret": config("REDDIT_API_CLIENT_SECRET"),
    "password": config("REDDIT_API_PASSWORD"),
    "user_agent": config("REDDIT_API_USER_AGENT"),
    "username": config("REDDIT_API_USERNAME"),
}

